import { Persona, FormState } from './types'

export const PERSONAS: Persona[] = [

  // ── PUSH ──────────────────────────────────────────────────────────────────

  {
    id: 1,
    name: 'Kavya',
    title: 'The Flash Sale Hunter',
    description: 'Teacher, 27 · Mumbai',
    channel: 'push',
    channelReason: 'Cart abandon + flash sale ending 2 days → instant push nudge before she goes elsewhere',
    tags: ['push', 'cart_abandon', 'flash_sale'],
    tagColors: ['coral', 'amber', 'teal'],
    customer_profile: {
      name: 'Kavya Patel',
      age: 27,
      occupation: 'Teacher',
      city: 'Mumbai',
      past_orders: 5,
      avg_order_value: 18000,
      last_purchase_days_ago: 4,
      lifetime_value_inr: 95000,
      return_rate_percent: 5,
      account_age_days: 380,
      last_messaged_hours_ago: 48,
      rfm_score: 78,
      loyalty_tier: 'silver',
      preferred_category: 'smartphones',
      preferred_brands: ['Redmi', 'Realme', 'Samsung'],
      opted_in_channels: ['push', 'whatsapp'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'cart_abandon',
      device: 'mobile',
      time_of_day: 19,
      session_duration_minutes: 12,
      traffic_source: 'email_campaign',
      entry_type: 'external_email_campaign',
      external_search_query: '',
      internal_search_queries: ['redmi note 13', 'best phone 20k'],
      categories_explored: ['smartphones'],
      pdp_visits_before: 3,
      sku_viewed: 'Redmi Note 13 Pro',
      times_viewed_this_sku_in_7_days: 5,
      search_query: '',
      scroll_depth_percent: 88,
      time_on_page_seconds: 460,
      heatmap_hotspots: ['price_section', 'delivery_date', 'reviews'],
      cart_state: 'added_to_cart',
      wishlist_contains_this_sku: true,
      session_actions: ['viewed_3_images', 'checked_delivery', 'read_reviews'],
      emi_calculator_used: true,
      coupon_searched: false,
      competitor_products_viewed: [],
      video_watched: false,
      price_comparison_done: false,
      reviews_read: true,
      upcoming_sale: 'Big Billion Day - 2 days left',
    },
  },

  {
    id: 2,
    name: 'Rohan',
    title: 'The Cart Abandoner',
    description: 'Engineer, 30 · Pune',
    channel: 'push',
    channelReason: 'High-value item in cart + sale ending tonight → push to close before midnight',
    tags: ['push', 'high_intent', 'sale_tonight'],
    tagColors: ['coral', 'purple', 'amber'],
    customer_profile: {
      name: 'Rohan Joshi',
      age: 30,
      occupation: 'Software Engineer',
      city: 'Pune',
      past_orders: 7,
      avg_order_value: 42000,
      last_purchase_days_ago: 7,
      lifetime_value_inr: 310000,
      return_rate_percent: 8,
      account_age_days: 720,
      last_messaged_hours_ago: 72,
      rfm_score: 82,
      loyalty_tier: 'gold',
      preferred_category: 'smartphones',
      preferred_brands: ['OnePlus', 'Samsung'],
      opted_in_channels: ['push', 'email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'cart_abandon',
      device: 'mobile',
      time_of_day: 22,
      session_duration_minutes: 18,
      traffic_source: 'direct_app',
      entry_type: 'internal_site_search',
      external_search_query: '',
      internal_search_queries: ['oneplus 12', 'oneplus 12 vs samsung s24'],
      categories_explored: ['smartphones', 'accessories'],
      pdp_visits_before: 4,
      sku_viewed: 'OnePlus 12',
      times_viewed_this_sku_in_7_days: 6,
      search_query: '',
      scroll_depth_percent: 91,
      time_on_page_seconds: 580,
      heatmap_hotspots: ['price_section', 'specs', 'emi_section'],
      cart_state: 'added_to_cart',
      wishlist_contains_this_sku: true,
      session_actions: ['viewed_3_images', 'used_compare', 'checked_delivery'],
      emi_calculator_used: true,
      coupon_searched: true,
      competitor_products_viewed: ['Samsung Galaxy S24'],
      video_watched: true,
      price_comparison_done: true,
      reviews_read: true,
      upcoming_sale: 'Sale ends tonight at midnight',
    },
  },

  {
    id: 3,
    name: 'Nikhil',
    title: 'The Silent Searcher',
    description: 'Student, 21 · Bangalore',
    channel: 'push',
    channelReason: '4 laptop searches over 2 days, never hit a PDP → proactive push with top recommendation',
    tags: ['push', 'search_without_pdp', 'high_intent'],
    tagColors: ['coral', 'teal', 'amber'],
    customer_profile: {
      name: 'Nikhil Sharma',
      age: 21,
      occupation: 'Engineering Student',
      city: 'Bangalore',
      past_orders: 2,
      avg_order_value: 12000,
      last_purchase_days_ago: 45,
      lifetime_value_inr: 28000,
      return_rate_percent: 0,
      account_age_days: 150,
      last_messaged_hours_ago: null,
      rfm_score: 38,
      loyalty_tier: 'bronze',
      preferred_category: 'laptops',
      preferred_brands: ['ASUS', 'HP', 'Lenovo'],
      opted_in_channels: ['push', 'email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'search_without_pdp',
      device: 'mobile',
      time_of_day: 21,
      session_duration_minutes: 22,
      traffic_source: 'google_generic',
      entry_type: 'internal_site_search',
      external_search_query: 'best laptop for coding under 50000',
      internal_search_queries: ['gaming laptop under 50k', 'best laptop for coding', 'i7 16gb ram laptop', 'asus laptop student'],
      categories_explored: ['laptops', 'accessories'],
      pdp_visits_before: 0,
      sku_viewed: '',
      times_viewed_this_sku_in_7_days: 0,
      search_query: 'gaming laptop under 50k',
      scroll_depth_percent: 35,
      time_on_page_seconds: 90,
      heatmap_hotspots: ['price_section'],
      cart_state: 'empty',
      wishlist_contains_this_sku: false,
      session_actions: [],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: [],
      video_watched: false,
      price_comparison_done: false,
      reviews_read: false,
      upcoming_sale: '',
    },
  },

  // ── EMAIL ──────────────────────────────────────────────────────────────────

  {
    id: 4,
    name: 'Arjun',
    title: 'The Lapsed User',
    description: 'Freelancer, 29 · Pune',
    channel: 'email',
    channelReason: '95 days inactive + RFM 28 + came from competitor search → win-back email',
    tags: ['email', 'lapsed_95d', 'rfm_28'],
    tagColors: ['teal', 'coral', 'amber'],
    customer_profile: {
      name: 'Arjun Kapoor',
      age: 29,
      occupation: 'Freelancer',
      city: 'Pune',
      past_orders: 2,
      avg_order_value: 12000,
      last_purchase_days_ago: 95,
      lifetime_value_inr: 24000,
      return_rate_percent: 15,
      account_age_days: 400,
      last_messaged_hours_ago: 72,
      rfm_score: 28,
      loyalty_tier: 'none',
      preferred_category: 'smartphones',
      preferred_brands: ['OnePlus'],
      opted_in_channels: ['email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'pdp_visit',
      device: 'desktop',
      time_of_day: 14,
      session_duration_minutes: 4,
      traffic_source: 'google_competitor_search',
      entry_type: 'external_competitor_search',
      external_search_query: 'oneplus 12 amazon vs flipkart',
      internal_search_queries: [],
      categories_explored: ['smartphones'],
      pdp_visits_before: 1,
      sku_viewed: 'OnePlus 12',
      times_viewed_this_sku_in_7_days: 1,
      search_query: 'oneplus 12 amazon',
      scroll_depth_percent: 34,
      time_on_page_seconds: 120,
      heatmap_hotspots: ['price_section'],
      cart_state: 'empty',
      wishlist_contains_this_sku: false,
      session_actions: [],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: ['OnePlus 12 (Amazon)'],
      video_watched: false,
      price_comparison_done: true,
      reviews_read: false,
      upcoming_sale: '',
    },
  },

  {
    id: 5,
    name: 'Divya',
    title: 'The Dormant',
    description: 'HR Manager, 33 · Chennai',
    channel: 'email',
    channelReason: '62 days gone + 1 past order + organic search → reactivation email with comparison guide',
    tags: ['email', 'dormant_62d', 'low_rfm'],
    tagColors: ['teal', 'coral', 'gray'],
    customer_profile: {
      name: 'Divya Menon',
      age: 33,
      occupation: 'HR Manager',
      city: 'Chennai',
      past_orders: 1,
      avg_order_value: 9500,
      last_purchase_days_ago: 62,
      lifetime_value_inr: 9500,
      return_rate_percent: 0,
      account_age_days: 200,
      last_messaged_hours_ago: null,
      rfm_score: 22,
      loyalty_tier: 'none',
      preferred_category: 'smartphones',
      preferred_brands: ['Samsung'],
      opted_in_channels: ['email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'pdp_visit',
      device: 'desktop',
      time_of_day: 11,
      session_duration_minutes: 5,
      traffic_source: 'google_generic',
      entry_type: 'external_organic_search',
      external_search_query: 'best samsung phone 2024',
      internal_search_queries: [],
      categories_explored: ['smartphones'],
      pdp_visits_before: 1,
      sku_viewed: 'Samsung Galaxy S24',
      times_viewed_this_sku_in_7_days: 1,
      search_query: 'best samsung phone 2024',
      scroll_depth_percent: 35,
      time_on_page_seconds: 140,
      heatmap_hotspots: ['price_section', 'specs'],
      cart_state: 'empty',
      wishlist_contains_this_sku: false,
      session_actions: [],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: [],
      video_watched: false,
      price_comparison_done: false,
      reviews_read: false,
      upcoming_sale: '',
    },
  },

  {
    id: 6,
    name: 'Meera',
    title: 'The New Visitor',
    description: 'Student, 22 · Chennai',
    channel: 'email',
    channelReason: 'First visit + zero purchase history + RFM 10 → nurture email with comparison help',
    tags: ['email', 'new_visitor', 'rfm_10'],
    tagColors: ['teal', 'gray', 'amber'],
    customer_profile: {
      name: 'Meera Nair',
      age: 22,
      occupation: 'Student',
      city: 'Chennai',
      past_orders: 0,
      avg_order_value: 0,
      last_purchase_days_ago: 0,
      lifetime_value_inr: 0,
      return_rate_percent: 0,
      account_age_days: 3,
      last_messaged_hours_ago: null,
      rfm_score: 10,
      loyalty_tier: 'none',
      preferred_category: 'smartphones',
      preferred_brands: [],
      opted_in_channels: ['email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'pdp_visit',
      device: 'mobile',
      time_of_day: 16,
      session_duration_minutes: 3,
      traffic_source: 'google_generic',
      entry_type: 'external_organic_search',
      external_search_query: 'best phone under 25000 india 2024',
      internal_search_queries: [],
      categories_explored: ['smartphones'],
      pdp_visits_before: 0,
      sku_viewed: 'Nothing Phone 2a',
      times_viewed_this_sku_in_7_days: 1,
      search_query: 'best phone under 25000 india',
      scroll_depth_percent: 28,
      time_on_page_seconds: 95,
      heatmap_hotspots: ['price_section', 'delivery_date'],
      cart_state: 'empty',
      wishlist_contains_this_sku: false,
      session_actions: [],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: [],
      video_watched: false,
      price_comparison_done: false,
      reviews_read: false,
      upcoming_sale: '',
    },
  },

  // ── WHATSAPP ──────────────────────────────────────────────────────────────

  {
    id: 7,
    name: 'Sneha',
    title: 'The Loyalist',
    description: 'Doctor, 35 · Hyderabad',
    channel: 'whatsapp',
    channelReason: 'Platinum loyalist + wishlist add + direct app visit → exclusive WhatsApp VIP offer',
    tags: ['whatsapp', 'platinum', 'wishlist_add'],
    tagColors: ['purple', 'teal', 'gray'],
    customer_profile: {
      name: 'Sneha Reddy',
      age: 35,
      occupation: 'Doctor',
      city: 'Hyderabad',
      past_orders: 12,
      avg_order_value: 45000,
      last_purchase_days_ago: 5,
      lifetime_value_inr: 580000,
      return_rate_percent: 3,
      account_age_days: 1200,
      last_messaged_hours_ago: null,
      rfm_score: 91,
      loyalty_tier: 'platinum',
      preferred_category: 'smartphones',
      preferred_brands: ['Apple'],
      opted_in_channels: ['whatsapp', 'push'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'wishlist_add',
      device: 'mobile',
      time_of_day: 18,
      session_duration_minutes: 20,
      traffic_source: 'direct',
      entry_type: 'direct',
      external_search_query: '',
      internal_search_queries: [],
      categories_explored: ['smartphones'],
      pdp_visits_before: 2,
      sku_viewed: 'iPhone 15',
      times_viewed_this_sku_in_7_days: 1,
      search_query: '',
      scroll_depth_percent: 92,
      time_on_page_seconds: 680,
      heatmap_hotspots: ['specs', 'camera_specs', 'reviews'],
      cart_state: 'has_other_items',
      wishlist_contains_this_sku: true,
      session_actions: ['viewed_3_images', 'read_reviews', 'checked_return_policy'],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: [],
      video_watched: true,
      price_comparison_done: false,
      reviews_read: true,
      upcoming_sale: '',
    },
  },

  {
    id: 8,
    name: 'Vikram',
    title: 'The Impulse Buyer',
    description: 'Banker, 41 · Delhi',
    channel: 'whatsapp',
    channelReason: 'Gold member + cart added + high AOV + direct app → personal WhatsApp to close the deal',
    tags: ['whatsapp', 'gold', 'added_to_cart'],
    tagColors: ['purple', 'pink', 'teal'],
    customer_profile: {
      name: 'Vikram Singh',
      age: 41,
      occupation: 'Banker',
      city: 'Delhi',
      past_orders: 8,
      avg_order_value: 62000,
      last_purchase_days_ago: 3,
      lifetime_value_inr: 520000,
      return_rate_percent: 5,
      account_age_days: 900,
      last_messaged_hours_ago: 48,
      rfm_score: 85,
      loyalty_tier: 'gold',
      preferred_category: 'headphones',
      preferred_brands: ['Sony', 'Bose'],
      opted_in_channels: ['whatsapp'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'cart_abandon',
      device: 'mobile',
      time_of_day: 21,
      session_duration_minutes: 15,
      traffic_source: 'direct_app',
      entry_type: 'direct',
      external_search_query: '',
      internal_search_queries: ['sony headphones', 'noise cancelling headphones'],
      categories_explored: ['headphones', 'accessories'],
      pdp_visits_before: 2,
      sku_viewed: 'Sony WH-1000XM5',
      times_viewed_this_sku_in_7_days: 2,
      search_query: '',
      scroll_depth_percent: 88,
      time_on_page_seconds: 540,
      heatmap_hotspots: ['specs', 'reviews', 'delivery_date'],
      cart_state: 'added_to_cart',
      wishlist_contains_this_sku: false,
      session_actions: ['viewed_3_images', 'read_reviews', 'checked_delivery'],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: ['Bose QC45'],
      video_watched: true,
      price_comparison_done: true,
      reviews_read: true,
      upcoming_sale: '',
    },
  },

  {
    id: 9,
    name: 'Rahul',
    title: 'The Deal Hunter',
    description: 'Marketing Mgr, 32 · Mumbai',
    channel: 'whatsapp',
    channelReason: 'Active deal seeker + EMI calc used + coupon searched → WhatsApp with price + EMI nudge',
    tags: ['whatsapp', 'deal_seeker', 'emi_checker'],
    tagColors: ['amber', 'coral', 'teal'],
    customer_profile: {
      name: 'Rahul Mehta',
      age: 32,
      occupation: 'Marketing Manager',
      city: 'Mumbai',
      past_orders: 3,
      avg_order_value: 8000,
      last_purchase_days_ago: 20,
      lifetime_value_inr: 26000,
      return_rate_percent: 20,
      account_age_days: 280,
      last_messaged_hours_ago: null,
      rfm_score: 45,
      loyalty_tier: 'bronze',
      preferred_category: 'smartphones',
      preferred_brands: ['Redmi', 'Realme'],
      opted_in_channels: ['whatsapp', 'email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'extended_dwell',
      device: 'mobile',
      time_of_day: 15,
      session_duration_minutes: 14,
      traffic_source: 'google_generic',
      entry_type: 'external_organic_search',
      external_search_query: 'best phone under 30000 india',
      internal_search_queries: ['redmi note 13', 'realme 12 pro'],
      categories_explored: ['smartphones'],
      pdp_visits_before: 3,
      sku_viewed: 'Redmi Note 13 Pro',
      times_viewed_this_sku_in_7_days: 2,
      search_query: 'best phone under 30000',
      scroll_depth_percent: 45,
      time_on_page_seconds: 180,
      heatmap_hotspots: ['price_section', 'emi_section'],
      cart_state: 'empty',
      wishlist_contains_this_sku: false,
      session_actions: [],
      emi_calculator_used: true,
      coupon_searched: true,
      competitor_products_viewed: ['Realme 12 Pro'],
      video_watched: false,
      price_comparison_done: true,
      reviews_read: false,
      upcoming_sale: '',
    },
  },

  {
    id: 10,
    name: 'Priya',
    title: 'The Deep Researcher',
    description: 'Software Engineer, 28 · Bangalore',
    channel: 'whatsapp',
    channelReason: 'Active + high scroll + wishlist + competitor search → WhatsApp comparison help with offer',
    tags: ['whatsapp', 'researcher', 'competitor_search'],
    tagColors: ['purple', 'teal', 'amber'],
    customer_profile: {
      name: 'Priya Sharma',
      age: 28,
      occupation: 'Software Engineer',
      city: 'Bangalore',
      past_orders: 6,
      avg_order_value: 55000,
      last_purchase_days_ago: 12,
      lifetime_value_inr: 350000,
      return_rate_percent: 8,
      account_age_days: 650,
      last_messaged_hours_ago: 36,
      rfm_score: 72,
      loyalty_tier: 'silver',
      preferred_category: 'smartphones',
      preferred_brands: ['Samsung', 'OnePlus'],
      opted_in_channels: ['whatsapp', 'email'],
      is_opted_out: false,
    },
    session_signals: {
      trigger_type: 'repeat_view',
      device: 'desktop',
      time_of_day: 20,
      session_duration_minutes: 28,
      traffic_source: 'google_competitor_search',
      entry_type: 'external_competitor_search',
      external_search_query: 'oneplus 12 vs samsung s24 comparison',
      internal_search_queries: ['samsung s24', 'oneplus 12'],
      categories_explored: ['smartphones'],
      pdp_visits_before: 5,
      sku_viewed: 'Samsung Galaxy S24',
      times_viewed_this_sku_in_7_days: 4,
      search_query: 'oneplus 12 vs samsung s24',
      scroll_depth_percent: 78,
      time_on_page_seconds: 420,
      heatmap_hotspots: ['emi_section', 'camera_specs', 'comparison_table'],
      cart_state: 'empty',
      wishlist_contains_this_sku: true,
      session_actions: ['viewed_3_images', 'checked_delivery', 'used_compare'],
      emi_calculator_used: false,
      coupon_searched: false,
      competitor_products_viewed: ['OnePlus 12', 'Pixel 8'],
      video_watched: true,
      price_comparison_done: true,
      reviews_read: true,
      upcoming_sale: '',
    },
  },
]

export const DEFAULT_FORM_STATE: FormState = {
  customer_profile: {
    name: '',
    age: 28,
    occupation: '',
    city: '',
    past_orders: 0,
    avg_order_value: 0,
    last_purchase_days_ago: 0,
    lifetime_value_inr: 0,
    return_rate_percent: 0,
    account_age_days: 0,
    last_messaged_hours_ago: null,
    rfm_score: 50,
    loyalty_tier: 'none',
    preferred_category: 'smartphones',
    preferred_brands: [],
    opted_in_channels: ['whatsapp', 'email', 'push'],
    is_opted_out: false,
  },
  session_signals: {
    trigger_type: 'pdp_visit',
    device: 'mobile',
    time_of_day: 14,
    session_duration_minutes: 5,
    traffic_source: 'google_generic',
    entry_type: 'external_organic_search',
    external_search_query: '',
    internal_search_queries: [],
    categories_explored: [],
    pdp_visits_before: 0,
    sku_viewed: '',
    times_viewed_this_sku_in_7_days: 1,
    search_query: '',
    scroll_depth_percent: 50,
    time_on_page_seconds: 120,
    heatmap_hotspots: [],
    cart_state: 'empty',
    wishlist_contains_this_sku: false,
    session_actions: [],
    emi_calculator_used: false,
    coupon_searched: false,
    competitor_products_viewed: [],
    video_watched: false,
    price_comparison_done: false,
    reviews_read: false,
    upcoming_sale: '',
  },
}

const ENTRY_TYPES = [
  'external_organic_search', 'external_paid_ad', 'external_social',
  'external_email_campaign', 'external_competitor_search',
  'internal_site_search', 'internal_browse', 'direct',
]

function jitter(value: number, pct = 0.1): number {
  const delta = value * pct
  return Math.max(0, Math.round(value + (Math.random() * 2 - 1) * delta))
}

export function randomiseForm(): FormState {
  const persona = PERSONAS[Math.floor(Math.random() * PERSONAS.length)]
  const cp = { ...persona.customer_profile }
  const ss = { ...persona.session_signals }

  cp.age = Math.max(18, Math.min(65, jitter(cp.age)))
  cp.past_orders = jitter(cp.past_orders)
  cp.avg_order_value = jitter(cp.avg_order_value)
  cp.last_purchase_days_ago = jitter(cp.last_purchase_days_ago)
  cp.rfm_score = Math.min(100, jitter(cp.rfm_score))
  cp.lifetime_value_inr = jitter(cp.lifetime_value_inr)
  cp.return_rate_percent = Math.min(50, jitter(cp.return_rate_percent))
  cp.account_age_days = jitter(cp.account_age_days)
  if (cp.last_messaged_hours_ago !== null) {
    cp.last_messaged_hours_ago = jitter(cp.last_messaged_hours_ago)
  }

  ss.scroll_depth_percent = Math.min(100, jitter(ss.scroll_depth_percent))
  ss.time_on_page_seconds = jitter(ss.time_on_page_seconds)
  ss.times_viewed_this_sku_in_7_days = Math.max(0, jitter(ss.times_viewed_this_sku_in_7_days))
  ss.session_duration_minutes = Math.max(1, jitter(ss.session_duration_minutes))
  ss.time_of_day = Math.min(23, Math.max(0, jitter(ss.time_of_day, 0.2)))
  ss.entry_type = ENTRY_TYPES[Math.floor(Math.random() * ENTRY_TYPES.length)] as typeof ss.entry_type
  ss.internal_search_queries = [...persona.session_signals.internal_search_queries]
  ss.categories_explored = [...persona.session_signals.categories_explored]
  ss.competitor_products_viewed = [...persona.session_signals.competitor_products_viewed]
  cp.opted_in_channels = [...persona.customer_profile.opted_in_channels]

  return { customer_profile: cp, session_signals: ss }
}
